<a href="https://colab.research.google.com/github/rijosudu123/ict-assessment/blob/main/data_aqusition_case_study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [338]:
import pandas as pd

In [339]:
population = pd.read_csv("/content/population.csv")
population

           country  population
0    United States   331002651
1            China  1411778724
2            India  1380004385
3            Japan   125836021
4          Germany    83240525
5   United Kingdom    67886011
6           France    65273511
7            Italy    60461826
8           Canada    38005238
9        Australia    25687041
10          Brazil   212559417
11          Russia   145934462
12     South Korea    51780579
13           Spain    46754778
14          Mexico   128932753
15       Indonesia   273523615
16    Saudi Arabia    34813871
17          Turkey    84339067
18    South Africa    59308690
19       Argentina    45195774
20     Netherlands    17441139
21     Switzerland     8654622
22          Sweden    10353442
23          Norway     5421241
24       Singapore     5850342

#Task 1
Read the Population dataset from the CSV file.
Hint:
● Use the pandas library.

● Display the first five rows.

● Check the shape and data types.

In [340]:
population.head(6)

          country  population
0   United States   331002651
1           China  1411778724
2           India  1380004385
3           Japan   125836021
4         Germany    83240525
5  United Kingdom    67886011

In [341]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     25 non-null     object
 1   population  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [342]:
population.shape

(25, 2)

#Task 2
Read the GDP dataset from the Excel file.
Hint:

● Use the appropriate pandas function.

● Display column names and data types.

In [343]:
gdp = pd.read_excel("/content/gdp.xlsx")
gdp

           Country       GDP
0    United States  30500000
1            China  19230000
2            India   4187000
3            Japan   4180000
4          Germany   4744000
5   United Kingdom   3839000
6           France   3211000
7            Italy   2420000
8           Canada   2250000
9        Australia   1880000
10          Brazil   2330000
11          Russia   2200000
12     South Korea   1800000
13           Spain   1710000
14          Mexico   1810000
15       Indonesia   1500000
16    Saudi Arabia   1100000
17          Turkey   1350000
18    South Africa    410000
19       Argentina    640000
20     Netherlands   1150000
21     Switzerland    940000
22          Sweden    650000
23          Norway    580000
24       Singapore    530000

In [344]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

#Task 3
Read the Internet Users dataset from the JSON file.

Hint:

● Use either the json module or pandas.

● Convert the data into a DataFrame.

In [345]:
interuser = pd.read_json("/content/internet_users.json")
interuser

           country  internet_users
0    United States       312000000
1            China      1080000000
2            India       850000000
3            Japan       118000000
4          Germany        79000000
5   United Kingdom        66000000
6           France        62000000
7            Italy        56000000
8           Canada        36000000
9        Australia        24000000
10          Brazil       181000000
11          Russia       125000000
12     South Korea        50000000
13           Spain        44000000
14          Mexico       102000000
15       Indonesia       212000000
16    Saudi Arabia        34000000
17          Turkey        69000000
18    South Africa        43000000
19       Argentina        41000000
20     Netherlands        17000000
21     Switzerland         8500000
22          Sweden        10100000
23          Norway         5300000
24       Singapore         5600000

#Task 4
Read the Literacy Rate dataset from the XML file.

Hint:

● Use xml.etree.ElementTree or pandas.read_xml().

● Extract all required fields into a DataFrame.

In [346]:
literacyrate = pd.read_xml("/content/literacy_rate.xml")
literacyrate

              name  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

#Task 5
Explore each dataset.

Find the following:

● Number of rows

● Number of columns

● Column names

● Data types

● Missing values

● Duplicate records

In [347]:
#pupolation
row_no1 = population.shape[0]
print(f"the row number in this dataset = {row_no1}")
column_no1 = population.shape[1]
print(f" the column number of this dataset = {column_no1}")
column_name = population.columns
column_name
population.dtypes
missing_value = population.isnull()
print(f"the missing values of this dataset = {missing_value.sum()}")
duplicated = population.duplicated()
print(f"the duplicated values of this dataset = {duplicated.sum()}")

the row number in this dataset = 25
 the column number of this dataset = 2
the missing values of this dataset = country       0
population    0
dtype: int64
the duplicated values of this dataset = 0

In [348]:
#gdp
row_no1 = gdp.shape[0]
print(f"the row number in this dataset = {row_no1}")
column_no1 = gdp.shape[1]
print(f" the column number of this dataset = {column_no1}")
column_name = gdp.columns
column_name
column_name = gdp.dtypes
missing_value = gdp.isnull()
print(f"the missing values of this dataset = {missing_value.sum()}")
duplicated = gdp.duplicated()
print(f"the duplicated values of this dataset = {duplicated.sum()}")

the row number in this dataset = 25
 the column number of this dataset = 2
the missing values of this dataset = Country    0
GDP        0
dtype: int64
the duplicated values of this dataset = 0

In [349]:
#interuser
row_no1 = interuser.shape[0]
print(f"the row number in this dataset = {row_no1}")
column_no1 = interuser.shape[1]
print(f" the column number of this dataset = {column_no1}")
column_name = interuser.columns
column_name
column_name = interuser.dtypes
missing_value = interuser.isnull()
print(f"the missing values of this dataset = {missing_value.sum()}")
duplicated =interuser.duplicated()
print(f"the duplicated values of this dataset = {duplicated.sum()}")

the row number in this dataset = 25
 the column number of this dataset = 2
the missing values of this dataset = country           0
internet_users    0
dtype: int64
the duplicated values of this dataset = 0

In [350]:
#literacyrate
row_no1 = literacyrate.shape[0]
print(f"the row number in this dataset = {row_no1}")
column_no1 = literacyrate.shape[1]
print(f" the column number of this dataset = {column_no1}")
column_name = literacyrate.columns
column_name
column_name = literacyrate.dtypes
missing_value = literacyrate.isnull()
print(f"the missing values of this dataset = {missing_value.sum()}")
duplicated =literacyrate.duplicated()
print(f"the duplicated values of this dataset = {duplicated.sum()}")

the row number in this dataset = 25
 the column number of this dataset = 2
the missing values of this dataset = name             0
literacy_rate    0
dtype: int64
the duplicated values of this dataset = 0

#Task 6
Rename columns wherever necessary so that all datasets have a common column
name for merging.
Hint:
● Example: Country → country

In [351]:
#gdp
gdp.rename(columns = {"Country" : "country"},inplace=True)
#literacyrate
literacyrate.rename(columns = {"name" : "country"},inplace = True)
gdp
literacyrate

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            India           77.7
3            Japan           99.0
4          Germany           99.0
5   United Kingdom           99.0
6           France           99.0
7            Italy           99.0
8           Canada           99.0
9        Australia           99.0
10          Brazil           93.2
11          Russia           99.7
12     South Korea           98.8
13           Spain           98.6
14          Mexico           95.4
15       Indonesia           96.0
16    Saudi Arabia           97.3
17          Turkey           96.7
18    South Africa           95.0
19       Argentina           99.1
20     Netherlands           99.0
21     Switzerland           99.0
22          Sweden           99.0
23          Norway          100.0
24       Singapore           97.5

#Task 7
Convert the required columns into appropriate numeric data types.

In [352]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     25 non-null     object
 1   population  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [353]:
gdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  25 non-null     object
 1   GDP      25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

In [354]:
literacyrate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        25 non-null     object
 1   literacy_rate  25 non-null     float64
dtypes: float64(1), object(1)
memory usage: 532.0+ bytes

In [355]:
interuser.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         25 non-null     object
 1   internet_users  25 non-null     int64
dtypes: int64(1), object(1)
memory usage: 532.0+ bytes

#Merge all four datasets into one DataFrame.
Hint:

● Use the common column (country)

● Choose an appropriate join method.

In [356]:
merge1 = pd.merge(population,gdp, on = "country",how = "inner")
merge2 = pd.merge(merge1,interuser, on = "country", how = "inner")
merge3 = pd.merge(merge2,literacyrate, on = "country", how = "inner")
merge3

           country  population       GDP  internet_users  literacy_rate
0    United States   331002651  30500000       312000000           99.0
1            China  1411778724  19230000      1080000000           97.2
2            India  1380004385   4187000       850000000           77.7
3            Japan   125836021   4180000       118000000           99.0
4          Germany    83240525   4744000        79000000           99.0
5   United Kingdom    67886011   3839000        66000000           99.0
6           France    65273511   3211000        62000000           99.0
7            Italy    60461826   2420000        56000000           99.0
8           Canada    38005238   2250000        36000000           99.0
9        Australia    25687041   1880000        24000000           99.0
10          Brazil   212559417   2330000       181000000           93.2
11          Russia   145934462   2200000       125000000           99.7
12     South Korea    51780579   1800000        50000000           98.8
13           Spain    46754778   1710000        44000000           98.6
14          Mexico   128932753   1810000       102000000           95.4
15       Indonesia   273523615   1500000       212000000           96.0
16    Saudi Arabia    34813871   1100000        34000000           97.3
17          Turkey    84339067   1350000        69000000           96.7
18    South Africa    59308690    410000        43000000           95.0
19       Argentina    45195774    640000        41000000           99.1
20     Netherlands    17441139   1150000        17000000           99.0
21     Switzerland     8654622    940000         8500000           99.0
22          Sweden    10353442    650000        10100000           99.0
23          Norway     5421241    580000         5300000          100.0
24       Singapore     5850342    530000         5600000           97.5

#Task 9
Create the following calculated columns:

1. Internet Penetration (%)

2. GDP Per Capita

In [357]:
merge3["internet_penetration (%)"] = (merge3['internet_users']/merge3['population'])*100
merge3["GDP per capital"] = merge3['GDP']/merge3['population']
merge3

,country,population,GDP,internet_users,literacy_rate,internet_penetration (%),GDP per capital
0,United States,331002651,30500000,312000000,99.0,94.259064,0.092144
1,China,1411778724,19230000,1080000000,97.2,76.499240,0.013621
2,India,1380004385,4187000,850000000,77.7,61.594007,0.003034
3,Japan,125836021,4180000,118000000,99.0,93.772832,0.033218
4,Germany,83240525,4744000,79000000,99.0,94.905696,0.056991
5,United Kingdom,67886011,3839000,66000000,99.0,97.221797,0.056551
6,France,65273511,3211000,62000000,99.0,94.984932,0.049193
7,Italy,60461826,2420000,56000000,99.0,92.620425,0.040025
8,Canada,38005238,2250000,36000000,99.0,94.723785,0.059202
9,Australia,25687041,1880000,24000000,99.0,93.432326,0.073189
10,Brazil,212559417,2330000,181000000,93.2,85.152661,0.010962
11,Russia,145934462,2200000,125000000,99.7,85.654888,0.015075
12,South Korea,51780579,1800000,50000000,98.8,96.561300,0.034762
13,Spain,46754778,1710000,44000000,98.6,94.108029,0.036574
14,Mexico,128932753,1810000,102000000,95.4,79.111008,0.014038
15,Indonesia,273523615,1500000,212000000,96.0,77.507019,0.005484
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.662222,0.031597
17,Turkey,84339067,1350000,69000000,96.7,81.812620,0.016007
18,South Africa,59308690,410000,43000000,95.0,72.502023,0.006913
19,Argentina,45195774,640000,41000000,99.1,90.716446,0.014161
20,Netherlands,17441139,1150000,17000000,99.0,97.470698,0.065936
21,Switzerland,8654622,940000,8500000,99.0,98.213417,0.108612
22,Sweden,10353442,650000,10100000,99.0,97.552099,0.062781
23,Norway,5421241,580000,5300000,100.0,97.763593,0.106987
24,Singapore,5850342,530000,5600000,97.5,95.720900,0.090593

#Task 10
Create a SQLite database. Store the final merged dataset into a table named

‘country_statistics’

Hint:

● Use the sqlite3 library.

● Load the DataFrame using pandas.

In [358]:
import sqlite3

try :
  conn = sqlite3.connect("country_statistics.db")
  merge3.to_sql("country_statistics",conn,if_exists="replace",index=False)
  print("Database created and connected successfully")
except sqlite3.Error as e :
  print("Error connecting to database",e)
finally :
  conn.close()

Database created and connected successfully

#Task 11
Verify that the data has been loaded successfully.

In [359]:
conn = sqlite3.connect("country_statistics.db")

query = "SELECT * FROM country_statistics"

result = pd.read_sql(query, conn)

print(result.head())

conn.close()

         country  population       GDP  internet_users  literacy_rate  \
0  United States   331002651  30500000       312000000           99.0
1          China  1411778724  19230000      1080000000           97.2
2          India  1380004385   4187000       850000000           77.7
3          Japan   125836021   4180000       118000000           99.0
4        Germany    83240525   4744000        79000000           99.0

   internet_penetration (%)  GDP per capital
0                 94.259064         0.092144
1                 76.499240         0.013621
2                 61.594007         0.003034
3                 93.772832         0.033218
4                 94.905696         0.056991

#Part E – Data Analysis Using Pandas
1 List the Top 5 countries by GDP.

In [360]:
merge3[["country","GDP"]].sort_values(by = "GDP",ascending = False).head(6)

          country       GDP
0   United States  30500000
1           China  19230000
4         Germany   4744000
2           India   4187000
3           Japan   4180000
5  United Kingdom   3839000

2 List the Top 5 countries by population.

In [361]:
merge3[["country","population"]].sort_values(by = "population",ascending = False).head(6)

          country  population
1           China  1411778724
2           India  1380004385
0   United States   331002651
15      Indonesia   273523615
10         Brazil   212559417
11         Russia   145934462

3 Calculate the average literacy rate.

In [362]:
avg_lit = merge3["literacy_rate"].mean()
avg_lit

np.float64(97.248)

 List all countries having a literacy rate greater than 90%.

In [363]:
merge3[merge3["literacy_rate"]>90]

,country,population,GDP,internet_users,literacy_rate,internet_penetration (%),GDP per capital
0,United States,331002651,30500000,312000000,99.0,94.259064,0.092144
1,China,1411778724,19230000,1080000000,97.2,76.499240,0.013621
3,Japan,125836021,4180000,118000000,99.0,93.772832,0.033218
4,Germany,83240525,4744000,79000000,99.0,94.905696,0.056991
5,United Kingdom,67886011,3839000,66000000,99.0,97.221797,0.056551
6,France,65273511,3211000,62000000,99.0,94.984932,0.049193
7,Italy,60461826,2420000,56000000,99.0,92.620425,0.040025
8,Canada,38005238,2250000,36000000,99.0,94.723785,0.059202
9,Australia,25687041,1880000,24000000,99.0,93.432326,0.073189
10,Brazil,212559417,2330000,181000000,93.2,85.152661,0.010962
11,Russia,145934462,2200000,125000000,99.7,85.654888,0.015075
12,South Korea,51780579,1800000,50000000,98.8,96.561300,0.034762
13,Spain,46754778,1710000,44000000,98.6,94.108029,0.036574
14,Mexico,128932753,1810000,102000000,95.4,79.111008,0.014038
15,Indonesia,273523615,1500000,212000000,96.0,77.507019,0.005484
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.662222,0.031597
17,Turkey,84339067,1350000,69000000,96.7,81.812620,0.016007
18,South Africa,59308690,410000,43000000,95.0,72.502023,0.006913
19,Argentina,45195774,640000,41000000,99.1,90.716446,0.014161
20,Netherlands,17441139,1150000,17000000,99.0,97.470698,0.065936
21,Switzerland,8654622,940000,8500000,99.0,98.213417,0.108612
22,Sweden,10353442,650000,10100000,99.0,97.552099,0.062781
23,Norway,5421241,580000,5300000,100.0,97.763593,0.106987
24,Singapore,5850342,530000,5600000,97.5,95.720900,0.090593

5 List all countries having an internet penetration greater than 70%.

In [364]:
merge3[merge3["internet_penetration (%)"] > 70]

,country,population,GDP,internet_users,literacy_rate,internet_penetration (%),GDP per capital
0,United States,331002651,30500000,312000000,99.0,94.259064,0.092144
1,China,1411778724,19230000,1080000000,97.2,76.499240,0.013621
3,Japan,125836021,4180000,118000000,99.0,93.772832,0.033218
4,Germany,83240525,4744000,79000000,99.0,94.905696,0.056991
5,United Kingdom,67886011,3839000,66000000,99.0,97.221797,0.056551
6,France,65273511,3211000,62000000,99.0,94.984932,0.049193
7,Italy,60461826,2420000,56000000,99.0,92.620425,0.040025
8,Canada,38005238,2250000,36000000,99.0,94.723785,0.059202
9,Australia,25687041,1880000,24000000,99.0,93.432326,0.073189
10,Brazil,212559417,2330000,181000000,93.2,85.152661,0.010962
11,Russia,145934462,2200000,125000000,99.7,85.654888,0.015075
12,South Korea,51780579,1800000,50000000,98.8,96.561300,0.034762
13,Spain,46754778,1710000,44000000,98.6,94.108029,0.036574
14,Mexico,128932753,1810000,102000000,95.4,79.111008,0.014038
15,Indonesia,273523615,1500000,212000000,96.0,77.507019,0.005484
16,Saudi Arabia,34813871,1100000,34000000,97.3,97.662222,0.031597
17,Turkey,84339067,1350000,69000000,96.7,81.812620,0.016007
18,South Africa,59308690,410000,43000000,95.0,72.502023,0.006913
19,Argentina,45195774,640000,41000000,99.1,90.716446,0.014161
20,Netherlands,17441139,1150000,17000000,99.0,97.470698,0.065936
21,Switzerland,8654622,940000,8500000,99.0,98.213417,0.108612
22,Sweden,10353442,650000,10100000,99.0,97.552099,0.062781
23,Norway,5421241,580000,5300000,100.0,97.763593,0.106987
24,Singapore,5850342,530000,5600000,97.5,95.720900,0.090593

 List the Top 5 countries by GDP per capita.

In [365]:
merge3[["country","GDP per capital"]].sort_values(by = "GDP per capital").head(6)

         country  GDP per capital
2          India         0.003034
15     Indonesia         0.005484
18  South Africa         0.006913
10        Brazil         0.010962
1          China         0.013621
14        Mexico         0.014038

 Calculate the total population represented in the dataset.

In [366]:
total = merge3["population"].sum()
total

np.int64(4720039725)

8 Calculate the average internet penetration across all countries.

In [367]:
a = merge3["internet_penetration (%)"].mean()
a

np.float64(89.6609210897238)

Identify the country having the highest number of internet users.

In [368]:
merge3.sort_values(by = "internet_users",ascending = False).head(1)

,country,population,GDP,internet_users,literacy_rate,internet_penetration (%),GDP per capital
1,China,1411778724,19230000,1080000000,97.2,76.49924,0.013621

In [369]:
correlation = merge3["literacy_rate"].corr(merge3["internet_penetration (%)"])

print("Correlation =", correlation)

Correlation = 0.7727536531179539

Answer the following questions using SQLite queries.

11 Display the Top 5 countries by GDP.

12 Find the average literacy rate.

13 Display all countries having literacy rate above 90%.

14 Find the Top 5 countries with the highest internet penetration.

15 Calculate the total population.

16 Find the country with the highest GDP per capita.

17 Export the final merged dataset as a CSV file.
  
18 Sort the dataset in descending order of GDP per Capita and display the Top 10
countries.

In [370]:
import sqlite3

conn = sqlite3.connect("country_statistics.db")
cursor = conn.cursor()
query = """
SELECT country, GDP
FROM country_statistics
ORDER BY GDP DESC
LIMIT 5
"""

pd.read_sql(query, conn)

         country       GDP
0  United States  30500000
1          China  19230000
2        Germany   4744000
3          India   4187000
4          Japan   4180000

In [371]:
query = """
SELECT AVG(literacy_rate) AS average_literacy_rate
FROM country_statistics
"""

pd.read_sql(query, conn)

   average_literacy_rate
0                 97.248

In [372]:
query = """
SELECT country, literacy_rate
FROM country_statistics
WHERE literacy_rate > 90
"""

pd.read_sql(query, conn)

           country  literacy_rate
0    United States           99.0
1            China           97.2
2            Japan           99.0
3          Germany           99.0
4   United Kingdom           99.0
5           France           99.0
6            Italy           99.0
7           Canada           99.0
8        Australia           99.0
9           Brazil           93.2
10          Russia           99.7
11     South Korea           98.8
12           Spain           98.6
13          Mexico           95.4
14       Indonesia           96.0
15    Saudi Arabia           97.3
16          Turkey           96.7
17    South Africa           95.0
18       Argentina           99.1
19     Netherlands           99.0
20     Switzerland           99.0
21          Sweden           99.0
22          Norway          100.0
23       Singapore           97.5

In [373]:
query = """
SELECT country, [Internet_penetration (%)]
FROM country_statistics
ORDER BY [Internet_penetration (%)] DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

        country  internet_penetration (%)
0   Switzerland                 98.213417
1        Norway                 97.763593
2  Saudi Arabia                 97.662222
3        Sweden                 97.552099
4   Netherlands                 97.470698

In [374]:
query = """
SELECT SUM(population) AS total_population
FROM country_statistics
"""

pd.read_sql(query, conn)

   total_population
0        4720039725

In [375]:
query = """
SELECT country,
(GDP*1.0/population) AS GDP_per_capita
FROM country_statistics
ORDER BY GDP_per_capita DESC
LIMIT 1
"""

pd.read_sql(query, conn)

       country  GDP_per_capita
0  Switzerland        0.108612

In [376]:
query = "SELECT * FROM country_statistics"

df = pd.read_sql(query, conn)

df.to_csv(
    "final_merged_dataset.csv",
    index=False
)

print("Exported")

Exported

In [377]:
query = """
SELECT country,
GDP,
population,
(GDP*1.0/population) AS GDP_per_capita
FROM country_statistics
ORDER BY GDP_per_capita DESC
LIMIT 10
"""

pd.read_sql(query, conn)

          country       GDP  population  GDP_per_capita
0     Switzerland    940000     8654622        0.108612
1          Norway    580000     5421241        0.106987
2   United States  30500000   331002651        0.092144
3       Singapore    530000     5850342        0.090593
4       Australia   1880000    25687041        0.073189
5     Netherlands   1150000    17441139        0.065936
6          Sweden    650000    10353442        0.062781
7          Canada   2250000    38005238        0.059202
8         Germany   4744000    83240525        0.056991
9  United Kingdom   3839000    67886011        0.056551

Write a short summary (5–6 points) explaining your ETL process, including:

● Data sources used

● Data cleaning steps

● Transformations performed

● Database loading process

● Key insights obtained from the analysis

1. Data Sources Used
Collected data from multiple file formats:
gdp.xlsx → GDP data
literacy_rate.xml → Literacy rate data
population.csv → Population data
internet_users.json → Internet usage data
Each dataset contained country-wise statistics.

2. Data Cleaning Steps
Loaded datasets into Pandas DataFrames.
Checked data structure using .info() and verified column names.
Checked for missing/null values using .isnull() and .sum().
Converted columns into appropriate data types (int64, float64, object).Ensured consistency in the common column country.
3. Transformations Performed
Merged all four datasets using country as the common key.
Used inner join to combine only matching records.
Created derived columns:
Internet Penetration = (internet_users / population) × 100
GDP per Capita = GDP / population
Sorted and analyzed the transformed dataset.

4. Database Loading Process
Created a SQLite database using the sqlite3 library.
Loaded the final merged DataFrame into the table country_statistics using Pandas to_sql().
Stored the processed dataset for SQL-based querying and analysis.

5. Data Analysis Performed
Identified the Top 5 countries by GDP.
Calculated average literacy rate and total population.
Found countries with literacy rate above 90%.
Determined Top countries by internet penetration and highest GDP per capita.

6. Key Insights Obtained
Countries with higher literacy rates generally showed higher internet penetration.
GDP per capita helped compare economic performance more accurately than total GDP.
Data integration from multiple sources enabled more meaningful country-level analysis.