<a href="https://colab.research.google.com/github/rijosudu123/ict-assessment/blob/main/numpy_pandas_coding_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###NUMPY

In [ ]:
import numpy as np

1. Create a NumPy array with values from 10 to 49 (inclusive).


● Reshape it into a 4x10 matrix.


● Then extract the last column from the reshaped matrix

In [ ]:
a = np.arange(10,50)
print(a)
b = a.reshape(4,10)
print(b)
c = b[0:,9:]
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[[19]
 [29]
 [39]
 [49]]

2. Create two 3×3 matrices:
One filled with all 5s , One with values from 1 to 9


● Add the two matrices


● Multiply them element-wise


● Then find the transpose of the result

In [ ]:
a = np.array(
    [
        [5,5,5],
        [5,5,5],
        [5,5,5]
    ]

)
print(a)
b = np.arange(1,10)
c = b.reshape(3,3)
print(c)
d = a + c
print(d)
e = a * c
print(e)
f = np.transpose(e)
print(f)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[ 5 20 35]
 [10 25 40]
 [15 30 45]]

3.Create a NumPy array of 15 random integers between 10 and 100.


● Replace all values greater than 50 with -1


● Count how many values were replaced.

In [ ]:
a = np.random.randint(10,100,size=(3,5))
print(a)
count = np.sum(a>50)
a[a>50]=-1
print(a)
print(f'The total modified vallues are {count}')

[[18 31 82 25 48]
 [15 95 16 46 24]
 [18 86 25 14 34]]
[[18 31 -1 25 48]
 [15 -1 16 46 24]
 [18 -1 25 14 34]]
The total modified vallues are 3

4. Generate a 5×4 array with random values between 0 and 1 (float).


● Find the row with the maximum sum of values.


● Normalize each row using the formula:

In [ ]:
a = np.random.rand(5,4)
print(a)
row_sums = a.sum(axis=1)
print(row_sums)
max_index = np.argmax(row_sums)
print(a[max_index])

[[0.89704511 0.75910577 0.63917863 0.16631435]
 [0.1186768  0.05640918 0.14528845 0.36064544]
 [0.75691078 0.45671954 0.59584317 0.59769896]
 [0.52405338 0.88103877 0.82890576 0.94958185]
 [0.52583711 0.16504102 0.5787206  0.72709885]]
[2.46164387 0.68101987 2.40717245 3.18357975 1.99669759]
[0.52405338 0.88103877 0.82890576 0.94958185]

5. arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])


● Find all unique elements


● Find the duplicates (elements that appear more than once)

In [ ]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
print(np.unique(arr))
values, counts = np.unique(arr, return_counts=True)
duplicates = values[counts > 1]
print(duplicates)

[1 3 5 7 9]
[1 3 5]

6. Create a 6×6 NumPy array with values from 1 to 36.


● Extract the middle 4×4 submatrix.


● Then extract all even numbers from this submatrix.

In [ ]:
a = np.arange(1,37)
b = a.reshape(6,6)
print(b)
c = b[1:5,1:5]
print(c)
even = c[c % 2 == 0]
print(even)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
[ 8 10 14 16 20 22 26 28]

7. Generate an array of shape (3, 4) with values from 0 to 11.


● Reshape it to (2, 6)


● Then flatten it into a 1D array


● Convert the 1D array back to shape (4, 3)

In [ ]:
a = np.arange(0,12).reshape(3,4)
print(a)
b = a.reshape(2,6)
print(b)
c = b.flatten()
print(c)
d = c.reshape(4,3)
print(d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

8 . Create an array: a = np.array([[1, 2], [3, 4]])


● Append a new row [5, 6]


● Then append a new column [7, 8, 9]

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a)
b = np.array([5,6])
c = np.vstack((a,b))
print(c)
d = np.array([[7],[8],[9]])
e = np.hstack((c,d))
print(e)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]
 [5 6 9]]

9.
a = np.array([1, 2, 3])

b = np.array([4, 5, 6])

c = np.array([7, 8, 9])


● Join them into a single array


● Reshape the result into a 3×3 matrix


● Extract the diagonal elements

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
d = np.concatenate((a,b,c))
print(d)
e = d.reshape(3,3)
print(e)
f = np.diag(e)
print(f)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]

10. Create a NumPy array of integers from 1 to 20.


● Extract all values that are divisible by 3 or 5.


● Count how many such values exist.

In [ ]:
a = np.arange(1,21)
print(a)
b = a[(a%3 == 0) | (a%5 == 0)]
print(b)
print(len(b))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 3  5  6  9 10 12 15 18 20]
9

##PANDAS

In [ ]:
import pandas as pd

1. Load the Titanic dataset and display the first 10 rows.

In [ ]:
data = pd.read_csv('/content/titanic_dataset (1).csv')
data.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

2. Find the number of missing values in each column.

In [ ]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

3. Find the percentage of passengers who survived, grouped by gender.

In [ ]:
a = data.groupby('Sex')['Survived'].mean() * 100
a

Sex
female    74.203822
male      18.890815
Name: Survived, dtype: float64

4. Find the average, median, and standard deviation of passenger ages.

In [ ]:
avg= data['Age'].mean()
print(f'Average is {avg}')
med = data['Age'].median()
print(f'Median is {med}')
std = data['Age'].std()
print(f'Standard deviation is {std}')

Average is 29.69911764705882
Median is 28.0
Standard deviation is 14.526497332334044

5. Count how many passengers were in each class (pclass).

In [ ]:
a = data['Pclass'].value_counts()
a

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

6. Show all passengers who were female, under age 18, and survived.

In [ ]:
a = data[(data['Sex'] == 'female') & (data['Age'] < 18) & (data['Survived'] == 1)]
a

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
156,157,1,3,"Gilnagh, Miss. Katherine ""Katie""",female,16.00,0,0,35851,7.7333,NaN,Q
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
184,185,1,3,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,22.0250,NaN,S
208,209,1,3,"Carr, Miss. Helen ""Ellen""",female,16.00,0,0,367231,7.7500,NaN,Q
233,234,1,3,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,31.3875,NaN,S
237,238,1,2,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,26.2500,NaN,S
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.00,1,0,PC 17758,108.9000,C65,C
329,330,1,1,"Hippach, Miss. Jean Gertrude",female,16.00,0,1,111361,57.9792,B18,C
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
389,390,1,2,"Lehmann, Miss. Bertha",female,17.00,0,0,SC 1748,12.0000,NaN,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.00,1,2,113760,120.0000,B96 B98,S
446,447,1,2,"Mellinger, Miss. Madeleine Violet",female,13.00,0,1,250644,19.5000,NaN,S
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.00,0,1,3101298,12.2875,NaN,S
504,505,1,1,"Maioni, Miss. Roberta",female,16.00,0,0,110152,86.5000,B79,S
530,531,1,2,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,26.0000,NaN,S
535,536,1,2,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,26.2500,NaN,S
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
689,690,1,1,"Madill, Miss. Georgette Alexandra",female,15.00,0,1,24160,211.3375,B5,S
691,692,1,3,"Karun, Miss. Manca",female,4.00,0,1,349256,13.4167,NaN,C
720,721,1,2,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,33.0000,NaN,S
750,751,1,2,"Wells, Miss. Joan",female,4.00,1,1,29103,23.0000,NaN,S
777,778,1,3,"Emanuel, Miss. Virginia Ethel",female,5.00,0,0,364516,12.4750,NaN,S
780,781,1,3,"Ayoub, Miss. Banoura",female,13.00,0,0,2687,7.2292,NaN,C
781,782,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.00,1,0,17474,57.0000,B20,S
830,831,1,3,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.00,1,0,2659,14.4542,NaN,C
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C

7. Replace missing age values with the median age.

In [ ]:
data['Age'] = data['Age'].fillna(data['Age'].median())
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

8. Create a column age_group with values:

a. 'Child' for age < 18

b. 'Adult' for age 18–60

c. 'Senior' for age > 60


d. Use: apply() or np.where() or custom function

In [ ]:
data['age_group'] = data['Age'].apply(
    lambda x : 'Child' if x < 18
    else 'Adult' if x <= 60
    else 'Senior'
)
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult

9.  Display the top 5 passengers who paid the highest fare.

In [ ]:
top_5 = data.sort_values(by = 'Fare',ascending=False)
top_5.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_group
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,Adult
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,Adult
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,Adult
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,Adult
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S,Senior

10. Find the average fare paid, grouped by both pclass and sex.

In [ ]:
a=data.groupby(['Pclass','Sex'])['Fare'].mean()
a

Pclass  Sex
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

11. Rename the following columns:

a. 'sex' → 'gender'

b. 'fare' → 'ticket_fare'

In [ ]:
data.rename(columns={'Sex' : 'Gender' , 'Fare' : 'Ticket_fare'},inplace=True)
data

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Ticket_fare,Cabin,Embarked,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Adult
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Adult

12. Count the number of passengers who survived and didn’t survive, grouped by class.

In [ ]:
a = data.groupby(['Pclass'])['Survived'].value_counts()
a

Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

13. Find the average age of passengers grouped by both class and gender.

In [ ]:
a = data.groupby(['Pclass','Gender'])['Age'].mean()
a

Pclass  Gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: Age, dtype: float64